### PR TITLE
Export reports as Excel

### LINKED ISSUE #152: Export reports as Excel instead of CSV files
Switch from CsvHelper to ClosedXML to export Excel files instead of CSV files on the report page

### PR DESCRIPTION
**Pull request by patdnr**

### CODE REVIEW

**Comment by patdnr** [comment]
I have attached the sample Excel file below. Basically, IReadOnlyList causes an error in the InsertTable method from ClosedXML, so I have to create a new IEnumerable object.

[FMS_export_2022-12-08-00-22-20.905.xlsx](https://github.com/gaepdit/FMS/files/10182343/FMS_export_2022-12-08-00-22-20.905.xlsx)

**Comment by patdnr** [comment]
Everything is working. Below is the sample result

[FMS_Facility_export_2022-12-08-15-51-34.764.xlsx](https://github.com/gaepdit/FMS/files/10189393/FMS_Facility_export_2022-12-08-15-51-34.764.xlsx)

**Comment by patdnr** [comment]
Changed ToString() to the `Name` attribute to correctly getting the value.

[FMS_Facility_export_2022-12-09-10-39-21.276.xlsx](https://github.com/gaepdit/FMS/files/10196097/FMS_Facility_export_2022-12-09-10-39-21.276.xlsx)

**Review by dougwaldron — APPROVED** [review]
LGTM and a very nice improvement to the user experience!

**Comment by tom-karasch** [comment]
Very well done, Pat! I like your example project too. I am sorry for the delay. I thought I had already closed these.

**Pull request merged**
