### PR TITLE
Admin page cont

### LINKED ISSUE #87: Maintenance section

### PR DESCRIPTION
**Pull request by tom-karasch**
I think I figured out Pull Request now. 
Please review and do not be too harsh because we need to get this to the Program asap. I can perfect it after I do the migration scripts. Thanks ;)

### CODE REVIEW

**Comment by dougwaldron** [comment]
I couldn't run the app because you've removed GUIDs from the facility type seed data that are still in use in the facility seed data. For example: 
[this Facility Type](https://github.com/gaepdit/FMS/blob/32af79b5083cef1109898fa7f4e6e771efcde902/FMS.Infrastructure/SeedData/FacilityTypeSeedData.cs#L50) is used by several facilities.

**Comment by tom-karasch** [comment]
Ah, sorry. I didn't realize you were running seed data. It makes sense since you are modifying the tables. Just uncomment them, or do you want me to do it?

**Review by dougwaldron — APPROVED** [review]
I did some general cleanup for consistency, etc. A few items remain for future work:

* The DetailsComplianceOfficer page gives an inaccurate message if the ID is not an FMS User but is an active CO.
* DetailsComplianceOfficer had a lot of opportunity for null reference exceptions. I tried to address them, but it might be better to split out the new CO functionality from the edit functionality. That way you would know where the ID is coming from (app users table vs. CO table) and you don't have to do so much checking.

**Comment by tom-karasch** [comment]
Yes, I want to rethink the CO page. I wanted to put a second argument in the "Get" function to differentiate CO table and User table Guids, but couldn't figure out the correct ASP commands to make it work right. That would make the logic much more simplified and reduce all the null reference checks.

**Pull request merged**
