### PR TITLE
Fixed Decimal conversion and other logic and ASP Issues

### LINKED ISSUE #219: SqlException: Error converting data type numeric to decimal. [HTTP 200 returned while handling GET Request]
Raygun report https://app.raygun.com/crashreporting/26p0xsd/errors/162658265345 has more details about the error

### PR DESCRIPTION
**Pull request by tom-karasch**
- Fixed initial Error with SQL exception.
- Found and corrected other logic issues that look like they were caused with Merge previous Excel Export.
- Found and corrected Logic and Error reporting to user issues regarding Lat and Long in Map Search.

### CODE REVIEW

**Comment by tom-karasch** [comment]
Just a quick note. 
The logic in the Map.cshtml.cs file, the logic still seems a bit odd, I know. Sam's original logic worked fine for the initial input checks. I tried many different ways of reworking the logic when I changed the GeoCoordHelper Functions to work better. But, this is what I came up with that finally did not result in exceptions being thrown and still gives the correct outcomes to various input scenarios. I am sure I could make this better in the future when I can come back to it fresh. But, for now, it works fine, yet still shows logic redundancy in "Code Smell".

**Review by dougwaldron — CHANGES_REQUESTED** [review]
I agree that it could be streamlined, but it prevents the SQL exception, which was the highest priority. 

If you want to keep working on it, I feel like the three lat/long validation functions could be replaced with a single function (return an enum?) since they aren't really independent. For example, right now, you can enter a latitude and leave longitude blank and it returns as valid. Also, zeros should not be considered valid -- either both should be within the state boundary or both should be null.

Some other minor issues:

* If GeocodeLat/Lng are set, then the plain Lat/Long don't need to be validated.
* GeocodeLat/Lng aren't validated so `decimal.Parse(spec.GeocodeLat)` might throw an exception. Replace with `spec.Latitude = decimal.TryParse(spec.GeocodeLat, out var geoLat) ? geoLat : 0;`.
* If the `ModelState` is not valid, you can immediately return the Page. Don't set ShowResults to true.

**Comment by tom-karasch** [comment]
Doug, 
When we looked at this originally, you said that zeros were valid. That is why I kept them. This makes the logic more streamlined. I thought spec. GeoCodeLat was necessary for Google Maps API. I made a wrong assumption from what Sam had originally added.

**Comment by dougwaldron** [comment]
> Doug, When we looked at this originally, you said that zeros were valid. That is why I kept them. This makes the logic more streamlined. I thought spec. GeoCodeLat was necessary for Google Maps API. I made a wrong assumption from what Sam had originally added.

If the parameter type is `decimal`, null arguments are interpreted as zeros. Since you changed the parameter type to `decimal?` (a better approach), the coercion to zero no longer happens.

GeocodeLat is what the Google API returns if an address is entered (lat/long will be null). If lat/long are entered, GeocodeLat/Lng are null.

**Pull request merged**
